version: '3.9'

networks: 
  database-network:
      external: true
      name: database-network
volumes:

    crypto-database-data-volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/data/crypto/maria/data
    crypto-database-config-volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/data/crypto/maria/config

    crypto-influxdb-data-volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/data/crypto/influx/config
    crypto-influxdb-config-volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/data/crypto/influx/data
    graphana-provisioning:
    graphana-dashboards:
services:
    crypto-database:
        image: mariadb:latest
        volumes:
            - crypto-database-data-volume:/var/lib/mysql
            - crypto-database-config-volume:/etc/
        environment:
            - MARIADB_ROOT_PASSWORD=sexmeup44
            - MARIADB_DATABASE=crypto_database
            - MARIADB_USER=abstract
            - MARIADB_PASSWORD=sexmeup44
            - REPLICA_NUMBER={{.Task.Slot}}
        networks:
            - database-network    
        ports:
            - "3306:3306"
        # deploy:
        #     placement:
        #         constraints:
        #             - "node.role==manager"
        #     replicas: 1
        #     restart_policy:
        #         condition: on-failure
            # resources:
            #     limits:
            #         cpus: '0.50'
            #         memory: 2000M
            #     reservations:
            #         cpus: '0.25'
            #         memory: 1000M
    crypto-influxdb:
        image: influxdb:1.7.9
        networks:
            - database-network  
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=sexmeup44
        volumes:
            - crypto-influxdb-data-volume:/var/lib/influxdb
            - crypto-influxdb-config-volume:/etc/influxdb/
        ports:
            - "8086:8086"
        # deploy:
        #     placement:
        #         constraints:
        #             - "node.role==manager"
        #     replicas: 1
        #     restart_policy:
        #         condition: on-failure
            # resources:
            #     limits:
            #         cpus: '0.50'
            #         memory: 2000M
            #     reservations:
            #         cpus: '0.25'
            #         memory: 1000M

    grafana:
      image: "grafana/grafana"
      ports:
      - "3000:3000"
      environment:
        GF_PATHS_DATA : /var/lib/grafana
        GF_SECURITY_ADMIN_PASSWORD : kafka
      volumes:
      -  graphana-provisioning:/etc/grafana/provisioning
      -  graphana-dashboards:/var/lib/grafana/dashboards